### ISSUE TITLE
Support pypy-3.7

### ISSUE THREAD

**Issue by DorianGray** [qtile/qtile#2028]
# Issue description

I would personally love pypy support in qtile.
~~Tests already pass~~, but CI has some obstacles in the way

# Qtile version

d6f8a6b2bdb0a184d691e059db03ba0918063997 / master

# TODO

- [x] wait on github actions to support pypy-3.7
- [x]  wait on tox-gh-actions to support pypy-3.7
- [x] modify workflow and tox.ini to run on pypy-3.7

# Relevant links

https://github.com/actions/setup-python/issues/136
https://github.com/ymyzk/tox-gh-actions/issues/49
https://github.com/qtile/qtile/pull/2055

**Comment by DorianGray** [comment]
My PR got merged over on tox-gh-actions, but it might be a bit for a release.

**Comment by ramnes** [comment]
Cool, thanks! Let's get this done.

**Comment by DorianGray** [comment]
All set!

**Comment by m-col** [comment]
Could we get something added to the docs about this too? Perhaps a section about the different Python implementations (is that what pypy is?) that we support? Personally this is something I know very little about, but if there are benefits to be taken advantage of then I'd be interested to know how/why/which!

**Comment by DorianGray** [comment]
absolutely! As soon as the tests pass, lol

**Comment by DorianGray** [comment]
Ubuntu/github actions ship pypy3 built against tcl 8.5, not 8.6 like the rest of the pythons. This is the cause of the test failures :/ Looking for a workaround.

**Comment by DorianGray** [comment]
https://github.com/qtile/qtile/pull/2055 is update with all tests passing. I'll write up some docs and add them tomorrow.

**Comment by DorianGray** [comment]
docs added, also thanks to @m-col their removal of `tkinter` no need to skip tests depending on if python was built with a recent version of `tk` \o/

**Comment by DorianGray** [comment]
Complete =)
